baseURL: "https://blog.6adm.in"
languageCode: fr-fr
DefaultContentLanguage: fr
title: "Blog"
theme: PaperMod
params:
    env: production
    homeInfoParams:
        Title: "Bienvenue \U0001F44D"
        Content: "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information.\n\n**Albert Einstein**\n\nCe site a pour vocation de me servir de pense-bête. J’espère qu’à vous aussi, il vous sera utile …"
    socialIcons:
        - name: Github
          url: "https://github.com/sixadmin"
        - name: gitlab
          url: "https://gitlab.com/ModernMenu"
        - name: cv
          url: "https://6adm.in/wp-content/uploads/2022/04/Richard_CRUZ_CV.pdf"
        - name: linkedin
          url: "https://www.linkedin.com/in/richard-cruz-7a978687/"
    ShowShareButtons: true
    ShowReadingTime: true
    ShowCodeCopyButtons: true
    label:
      text: ""
      icon: img/logo.png
      iconHeight: 20

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
    - identifier: archives
      name: archives
      url: /archives/
      weight: 20
    - identifier: 6adm
      name: 6adm.in
      url: https://6adm.in
      weight: 30